######################################################################
# Automatically generated by qmake (3.0) ? 9? 14 11:17:26 2014
######################################################################

TEMPLATE = app
TARGET = MarkGame
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += markgame.h
SOURCES += main.cpp markgame.cpp
RESOURCES += markgame.qrc
