######################################################################
# Automatically generated by qmake (3.0) ? 9? 7 12:19:48 2014
######################################################################

TEMPLATE = app
TARGET = MarkGame
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
